---
# Use '-e "ufw=true"' with ansible-playbook or 'ufw: true' in your host vars
# to activate this. Rules are stored in '/lib/ufw/user{,6}.rules'.
#
# Afterwards, call manually:
#   egrep 'ssh|22' /lib/ufw/user.rules
#   ufw enable
#   ufw status verbose
#   ufw show user-rules | grep -B999 '^IPV6'

- name: Install UFW packages
  apt: name={{ item }} state=latest
  with_items:
    - ufw

- name: Enable UFW logging
  shell: "ufw status verbose | grep ^Logging.*low || ufw logging low"
  register: ufw_result
  failed_when: 'not("enabled" in ufw_result.stdout or "on (low)" in ufw_result.stdout)'
  changed_when: ("enabled" in ufw_result.stdout)

- name: Set UFW rules
  command: "ufw {{ item.action }} {{ item.to }}"
  register: ufw_result
  failed_when: not("Skipping" in ufw_result.stdout or "added" in ufw_result.stdout or "updated" in ufw_result.stdout)
  changed_when: ("added" in ufw_result.stdout or "updated" in ufw_result.stdout)
  with_items:
    - {action: limit, to: "22/tcp"}
    - {action: allow, to: "443/tcp"}
    - {action: allow, to: "64000:64042/tcp"}

- name: Get UFW status
  command: ufw status verbose
  changed_when: False
  register: ufw_status
- debug: var=ufw_status.stdout_lines
