force_cfg: no
main_rtrc_file: /home/rtorrent/rtorrent/rtorrent.rc
rutorrent_rtrc_file: "{{ main_rtrc_file }}"
rtorrent_bindir: /opt/rtorrent/bin/

# rtorrent.rc settings
rt_global_up_rate_kb: 800
rt_global_down_rate_kb: 100
rt_pieces_memory: 1800M
rt_xmlrpc_size_limit: 16M
rt_system_umask: 0027
rt_keys_layout: qwertz
